export type LigneBonLivraison = {
  DO_Piece: string;
  DL_LIGNE: string;
  AR_REF: string; // Code article (vide si commentaire)
  DL_QTEBL: string;
  QTE_DIFF_CMDE: string;
  DL_Design: string; // Description ou commentaire
  DL_PrixUnitaire: string;
  DL_MontantHT: string;
  Commentaires: string;
  Commentaires2: string;
  Famille_ART: string;
};

export type DocVente = {
  DO_Domaine: string;
  DO_Type: string;
  DO_Piece: string;
  cbDO_Piece: string;
  DO_Date: string;
  DO_Ref: string;
  DO_Tiers: string;
  cbDO_Tiers: string;
  CO_No: string;
  cbCO_No: string;
  DO_Period: string;
  DO_Devise: string;
  DO_Cours: string;
  DE_No: string;
  cbDE_No: string;
  LI_No: string;
  cbLI_No: string;
  CT_NumPayeur: string;
  cbCT_NumPayeur: string;
  DO_Expedit: string;
  DO_NbFacture: string;
  DO_BLFact: string;
  DO_TxEscompte: string;
  DO_Reliquat: string;
  DO_Imprim: string;
  CA_Num: string;
  cbCA_Num: string;
  DO_Coord01: string;
  DO_Coord02: string;
  DO_Coord03: string;
  DO_Coord04: string;
  DO_Souche: string;
  DO_DateLivr: string;
  DO_Condition: string;
  DO_Tarif: string;
  DO_Colisage: string;
  DO_TypeColis: string;
  DO_Transaction: string;
  DO_Langue: string;
  DO_Ecart: string;
  DO_Regime: string;
  N_CatCompta: string;
  DO_Ventile: string;
  AB_No: string;
  DO_DebutAbo: string;
  DO_FinAbo: string;
  DO_DebutPeriod: string;
  DO_FinPeriod: string;
  CG_Num: string;
  cbCG_Num: string;
  DO_Statut: string;
  DO_Heure: string;
  CA_No: string;
  cbCA_No: string;
  CO_NoCaissier: string;
  cbCO_NoCaissier: string;
  DO_Transfere: string;
  DO_Cloture: string;
  DO_NoWeb: string;
  DO_Attente: string;
  DO_Provenance: string;
  CA_NumIFRS: string;
  MR_No: string;
  DO_TypeFrais: string;
  DO_ValFrais: string;
  DO_TypeLigneFrais: string;
  DO_TypeFranco: string;
  DO_ValFranco: string;
  DO_TypeLigneFranco: string;
  DO_Taxe1: string;
  DO_TypeTaux1: string;
  DO_TypeTaxe1: string;
  DO_Taxe2: string;
  DO_TypeTaux2: string;
  DO_TypeTaxe2: string;
  DO_Taxe3: string;
  DO_TypeTaux3: string;
  DO_TypeTaxe3: string;
  DO_MajCpta: string;
  DO_Motif: string;
  CT_NumCentrale: string;
  cbCT_NumCentrale: string;
  DO_Contact: string;
  DO_FactureElec: string;
  DO_TypeTransac: string;
  DO_DateLivrRealisee: string;
  DO_DateExpedition: string;
  DO_FactureFrs: string;
  cbDO_FactureFrs: string;
  DO_PieceOrig: string;
  cbDO_PieceOrig: string;
  DO_GUID: string;
  DO_EStatut: string;
  DO_DemandeRegul: string;
  ET_No: string;
  cbET_No: string;
  DO_Valide: string;
  DO_Coffre: string;
  DO_CodeTaxe1: string;
  DO_CodeTaxe2: string;
  DO_CodeTaxe3: string;
  DO_TotalHT: string;
  DO_StatutBAP: string;
  DO_Escompte: string;
  DO_DocType: string;
  DO_TypeCalcul: string;
  DO_FactureFile: string;
  DO_TotalHTNet: string;
  DO_TotalTTC: string;
  DO_NetAPayer: string;
  DO_MontantRegle: string;
  DO_RefPaiement: string;
  DO_AdressePaiement: string;
  DO_PaiementLigne: string;
  DO_MotifDevis: string;
  DO_Conversion: string;
  cbProt: string;
  cbMarq: string;
  cbCreateur: string;
  cbModification: string;
  cbReplication: string;
  cbFlag: string;
  cbCreation: string;
  cbCreationUser: string;
  cbHash: string;
  cbHashVersion: string;
  cbHashDate: string;
  cbHashOrder: string;
  'BC client': string;
  'Créneau de livraison': string;
  'Personne à contacter sur place': string;
  'Adresse liv° / sce à livrer': string;
  'EXPE : ILE': string;
  'EXPE N° CSNT': string;
  'OBS. 1': string;
  'OBS. 2': string;
  'OBS. 3': string;
  'OBS. 4': string;
  'Cde saisie par': string;
  'Cde transmisse par': string;
  'Cde : mode de réception': string;
  'Heure début': string;
  DO_TVADebit: string;
  EB_No: string;
  DO_RefExterne: string;
  CFAR_No: string;
  cbCFAR_No: string;
  FAC_No: string;
  cbFAC_No: string;
  DO_Exclure: string;
  DO_CodeService: string;
};
