-- CreateTable
CREATE TABLE "raw_doc_vente" (
    "DO_Piece" TEXT NOT NULL,
    "cbDO_Piece" TEXT NOT NULL,
    "DO_GUID" TEXT NOT NULL,
    "DO_Domaine" TEXT NOT NULL,
    "DO_Type" TEXT NOT NULL,
    "DO_Date" TIMESTAMP(3) NOT NULL,
    "DO_Ref" TEXT NOT NULL,
    "DO_Souche" TEXT NOT NULL,
    "DO_Period" TEXT NOT NULL,
    "DO_Heure" TEXT NOT NULL,
    "DO_Statut" TEXT NOT NULL,
    "DO_EStatut" TEXT NOT NULL,
    "DO_DocType" TEXT NOT NULL,
    "DO_RefExterne" TEXT,
    "DO_NoWeb" TEXT,
    "DO_Tiers" TEXT NOT NULL,
    "cbDO_Tiers" TEXT NOT NULL,
    "CT_NumPayeur" TEXT NOT NULL,
    "cbCT_NumPayeur" TEXT NOT NULL,
    "CT_NumCentrale" TEXT,
    "cbCT_NumCentrale" TEXT,
    "DO_Contact" TEXT,
    "DO_Devise" TEXT NOT NULL,
    "DO_Cours" TEXT NOT NULL,
    "DO_TotalHT" DECIMAL(18,2) NOT NULL,
    "DO_TotalHTNet" DECIMAL(18,2) NOT NULL,
    "DO_TotalTTC" DECIMAL(18,2) NOT NULL,
    "DO_NetAPayer" DECIMAL(18,2) NOT NULL,
    "DO_MontantRegle" DECIMAL(18,2) NOT NULL,
    "DO_Escompte" DECIMAL(18,2) NOT NULL,
    "DO_TxEscompte" DECIMAL(5,2) NOT NULL,
    "DO_Ecart" DECIMAL(18,2),
    "DO_Taxe1" DECIMAL(18,2) NOT NULL,
    "DO_TypeTaux1" TEXT NOT NULL,
    "DO_TypeTaxe1" TEXT NOT NULL,
    "DO_CodeTaxe1" TEXT NOT NULL,
    "DO_Taxe2" DECIMAL(18,2) NOT NULL,
    "DO_TypeTaux2" TEXT NOT NULL,
    "DO_TypeTaxe2" TEXT NOT NULL,
    "DO_CodeTaxe2" TEXT NOT NULL,
    "DO_Taxe3" DECIMAL(18,2) NOT NULL,
    "DO_TypeTaux3" TEXT NOT NULL,
    "DO_TypeTaxe3" TEXT NOT NULL,
    "DO_CodeTaxe3" TEXT NOT NULL,
    "DO_TVADebit" TEXT,
    "DO_Expedit" TEXT,
    "DO_DateLivr" TIMESTAMP(3),
    "DO_DateLivrRealisee" TIMESTAMP(3),
    "DO_DateExpedition" TIMESTAMP(3),
    "DO_Colisage" TEXT,
    "DO_TypeColis" TEXT,
    "Créneau de livraison" TEXT,
    "Personne à contacter sur place" TEXT,
    "Adresse liv° / sce à livrer" TEXT,
    "CO_No" TEXT,
    "cbCO_No" TEXT,
    "DE_No" TEXT,
    "cbDE_No" TEXT,
    "LI_No" TEXT,
    "cbLI_No" TEXT,
    "CA_Num" TEXT,
    "cbCA_Num" TEXT,
    "CA_No" TEXT,
    "cbCA_No" TEXT,
    "CA_NumIFRS" TEXT,
    "CG_Num" TEXT,
    "cbCG_Num" TEXT,
    "ET_No" TEXT,
    "cbET_No" TEXT,
    "EB_No" TEXT,
    "CFAR_No" TEXT,
    "cbCFAR_No" TEXT,
    "FAC_No" TEXT,
    "cbFAC_No" TEXT,
    "DO_Coord01" TEXT,
    "DO_Coord02" TEXT,
    "DO_Coord03" TEXT,
    "DO_Coord04" TEXT,
    "DO_Condition" TEXT,
    "DO_Tarif" TEXT,
    "DO_TypeCalcul" TEXT,
    "DO_Conversion" TEXT,
    "DO_TypeFrais" TEXT,
    "DO_ValFrais" DECIMAL(18,2),
    "DO_TypeLigneFrais" TEXT,
    "DO_TypeFranco" TEXT,
    "DO_ValFranco" DECIMAL(18,2),
    "DO_TypeLigneFranco" TEXT,
    "DO_NbFacture" TEXT,
    "DO_BLFact" TEXT,
    "DO_Reliquat" TEXT,
    "DO_Imprim" TEXT,
    "DO_Ventile" TEXT,
    "DO_Transfere" TEXT,
    "DO_Cloture" TEXT,
    "DO_Attente" TEXT,
    "DO_Valide" TEXT,
    "DO_StatutBAP" TEXT,
    "DO_DemandeRegul" TEXT,
    "DO_Exclure" TEXT,
    "DO_RefPaiement" TEXT,
    "DO_AdressePaiement" TEXT,
    "DO_PaiementLigne" TEXT,
    "DO_Transaction" TEXT,
    "DO_TypeTransac" TEXT,
    "DO_Regime" TEXT,
    "N_CatCompta" TEXT,
    "DO_MajCpta" TEXT,
    "DO_Langue" TEXT,
    "DO_Provenance" TEXT,
    "DO_Motif" TEXT,
    "DO_MotifDevis" TEXT,
    "DO_FactureElec" TEXT,
    "DO_FactureFile" TEXT,
    "DO_FactureFrs" TEXT,
    "cbDO_FactureFrs" TEXT,
    "DO_PieceOrig" TEXT,
    "cbDO_PieceOrig" TEXT,
    "AB_No" TEXT,
    "DO_DebutAbo" TIMESTAMP(3),
    "DO_FinAbo" TIMESTAMP(3),
    "DO_DebutPeriod" TIMESTAMP(3),
    "DO_FinPeriod" TIMESTAMP(3),
    "CO_NoCaissier" TEXT,
    "cbCO_NoCaissier" TEXT,
    "DO_Coffre" TEXT,
    "EXPE : ILE" TEXT,
    "EXPE N° CSNT" TEXT,
    "OBS. 1" TEXT,
    "OBS. 2" TEXT,
    "OBS. 3" TEXT,
    "OBS. 4" TEXT,
    "BC client" TEXT,
    "Cde saisie par" TEXT,
    "Cde transmisse par" TEXT,
    "Cde : mode de réception" TEXT,
    "Heure début" TEXT,
    "MR_No" TEXT,
    "DO_CodeService" TEXT,
    "cbProt" INTEGER NOT NULL,
    "cbMarq" INTEGER NOT NULL,
    "cbCreateur" TEXT NOT NULL,
    "cbModification" TIMESTAMP(3) NOT NULL,
    "cbReplication" INTEGER NOT NULL,
    "cbFlag" INTEGER NOT NULL,
    "cbCreation" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cbCreationUser" TEXT NOT NULL,
    "cbHash" TEXT,
    "cbHashVersion" INTEGER,
    "cbHashDate" TIMESTAMP(3),
    "cbHashOrder" INTEGER,

    CONSTRAINT "raw_doc_vente_pkey" PRIMARY KEY ("DO_Piece")
);

-- CreateIndex
CREATE UNIQUE INDEX "raw_doc_vente_DO_GUID_key" ON "raw_doc_vente"("DO_GUID");

-- CreateIndex
CREATE INDEX "raw_doc_vente_DO_Tiers_idx" ON "raw_doc_vente"("DO_Tiers");

-- CreateIndex
CREATE INDEX "raw_doc_vente_DO_Date_idx" ON "raw_doc_vente"("DO_Date");

-- CreateIndex
CREATE INDEX "raw_doc_vente_DO_Statut_idx" ON "raw_doc_vente"("DO_Statut");

-- CreateIndex
CREATE INDEX "raw_doc_vente_DO_Type_idx" ON "raw_doc_vente"("DO_Type");

-- CreateIndex
CREATE INDEX "raw_doc_vente_CT_NumPayeur_idx" ON "raw_doc_vente"("CT_NumPayeur");
